
[ballerina.log]
# reco: comment this line in prod environnement
level = "DEBUG"

[job_patch.conf]
port = 9988

[update_customer_dispo.customerDispo]
dryRun = true
dryRunNotify = true

[zero_km.websocket]
port = 21003

[check_disk_space.conf]
server = "ELITEAUTO BO"
hour = 16
minutes = 0
seconds = 0
