[package]
org = "cosmobilis"
name = "check_funding_offers"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "cosmobilis"
name = "bo_db"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "job_patch"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "teams"
version = "0.1.0"
repository = "local"

