[package]
org = "cosmobilis"
name = "sync_fo_quotations"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "cosmobilis"
name = "fo_db"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "mysql5_bindings"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "bo_db"
version = "0.1.0"
repository = "local"

[[dependency]]
org = "cosmobilis"
name = "job_patch"
version = "0.1.0"
repository = "local"
